config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  root "users#index"

  get :signup, to: "users#new"
  post :signup, to: "users#create"

  get :login, to: "sessions#new"
  post :login, to: "sessions#create"
  delete :logout, to: "sessions#destroy"
  resources :roles
  resources :users
  resources :permissions, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :role

  def action_resource
    "#{action}##{resource}"
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :permissions

  def permission_values
    permissions.map(&:action_resource)
  end

  def permission_values=(action_resources)
    add = action_resources - permission_values
    delete = permission_values - action_resources

    delete.each do |action_resource|
      action, resource = action_resource.split("#", 2)
      permissions.select do |permission|
        permission.action == action && permission.resource == resource
      end.each(&:mark_for_destruction)
    end
    add.each do |action_resource|
      action, resource = action_resource.split("#", 2)
      permissions.build action: action, resource: resource
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_and_belongs_to_many :roles
  has_many :permissions, through: :roles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate

  helper_method :current_user, :login?

  private

    def authenticate
      redirect_to login_path unless login?
    end

    def login?
      !!current_user
    end

    def current_user
      @current_user ||= login_from_session unless defined?(@current_user)
      @current_user
    end

    def login_from_session
      User.find session[:user_id] if session[:user_id]
    rescue ActiveRecord::NotFound
      session[:user_id] = nil
    end

    def login_as(user)
      @current_user = user
      session[:user_id] = user.id
    end

    def not_login_required
      redirect_to root_path if login?
    end

    def logout
      @current_user = nil
      session[:user_id] = nil
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    authorize :dashboard
  end
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  # GET /permissions
  # GET /permissions.json
  def index
    @permissions = ApplicationPolicy.policies
  end

  # GET /permissions/1
  # GET /permissions/1.json
  def show
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
    @permissions = ApplicationPolicy.policies.flat_map do |policy|
      policy.actions.map do |action, action_desc|
        [ "#{policy.comment} - #{action_desc}", "#{action}##{policy.resource_name}"]
      end
    end
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, permission_values: [])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]
  before_action :not_login_required, only: [:new, :create]

  def new
  end

  def create
    @user = User.where(name: params[:name]).first
    if @user&.authenticate(params[:password])
      login_as @user
      redirect_to root_url
    else
      flash.not[:danger] = "name/password incorrect"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create, :index]
  before_action :not_login_required, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    authorize User
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    authorize @user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        login_as @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    authorize @user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, role_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoleBase</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if login? %>
      <%= link_to "Logout", logout_path, method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/permissions/_form.html.erb
<%= form_for(permission) do |f| %>
  <% if permission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(permission.errors.count, "error") %> prohibited this permission from being saved:</h2>

      <ul>
      <% permission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/permissions/edit.html.erb
<h1>Editing Permission</h1>

<%= render 'form', permission: @permission %>

<%= link_to 'Show', @permission %> |
<%= link_to 'Back', permissions_path %>

app/views/permissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Permissions</h1>

<table>
  <thead>
    <tr>
      <th>Resource</th>
      <th></th>
      <th>Action</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @permissions.each do |policy| %>
      <% policy.actions.each do |act, comment| %>
        <tr>
          <td><%= policy.resource_name %></td>
          <td><%= policy.comment %></td>
          <td><%= act %></td>
          <td><%= comment %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>

app/views/permissions/new.html.erb
<h1>New Permission</h1>

<%= render 'form', permission: @permission %>

<%= link_to 'Back', permissions_path %>

app/views/permissions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_permission_path(@permission) %> |
<%= link_to 'Back', permissions_path %>

app/views/roles/_form.html.erb
<%= form_for(role) do |f| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :permission_values %>
    <%= f.select :permission_values, options_for_select(@permissions, selected: f.object.permissions.map(&:action_resource)), {}, multiple: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>
<table>
  <tbody>
    <% @role.permissions.each do |per| %>
      <tr>
        <td><%= per.resource %></td>
        <td><%= per.action %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :role %>
    <%= f.collection_select :role_ids, Role.all, :id, :name, {selected: f.object.role_ids },  multiple: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Roles:</strong>
  <% @user.roles.each do |r| %>
    <%= r.name %>
  <% end %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>